vocali/Aplicaciones/urls.py
from django.urls import include, path
from django.contrib import admin
from rest_framework import routers


#DefaultRouter

from django.conf import settings
from django.conf.urls.static import static

from django import views
from . import views, api_views 

router = routers.DefaultRouter()
router.register(r'company', api_views.CompanyViewSet)
router.register(r'usr_company', api_views.Usr_companyViewSet)
router.register(r'folder', api_views.FolderViewSet)
router.register(r'tType_identity', api_views.tType_identityViewSet)
router.register(r'tLanguage', api_views.tLanguageViewSet)
router.register(r'tRoles_trans', api_views.tRoles_transViewSet)
router.register(r'tEtapas_trans', api_views.tEtapas_transViewSet)
router.register(r'tJson_trans', api_views.tJson_transViewSet)
router.register(r'tTranscript', api_views.tTranscriptViewSet)
router.register(r'tPerson', api_views.tPersonViewSet)
router.register(r'uploaded_file', api_views.UploadedFileViewSet)
router.register(r'tSpeakes_trans', api_views.tSpeaker_transViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include(router.urls)),

    path('contact/', views.contact_view, name='contact'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', views.profile_view, name='profile'),
    path('login/', views.login_view, name='login'),
    path('usersprofile/', views.usersprofile, name='usersprofile'),
    path('pagesfaq/', views.pagesfaq, name='pagesfaq'),
    path('pagescontact/', views.pagescontact, name='pagescontact'),
    path('principal/', views.principal, name='principal'),
    path('dashboard/', views.dashboard, name='dashboard'),


    path('api/folder/', views.FolderListCreateView.as_view(), name='folder-list-create'),
    path('api/folder/<int:pk>/', views.FolderRetrieveUpdateDestroyView.as_view(), name='folder-detail'),
# Tipos de identidad
    path('type_identity/', views.type_identity_view, name='type_identity'),
    path('createType_identity', views.tType_identityCreateView.as_view(),name='createType_identity'),
    path('updateType_identity/<int:pk>/', views.tType_identityUpdateView.as_view(),name='updateType_identity'),
    path('deleteType_identity/<int:pk>/', views.tType_identityDeleteView.as_view(),name='deleteType_identity'),
# Lenguajes
    path('tLanguage/', views.tLanguage_view, name='tLanguage'),
    path('createLanguage', views.tLanguageCreateView.as_view(),name='createLanguage'),
    path('updateLanguage/<int:pk>/', views.tLanguageUpdateView.as_view(),name='updateLanguage'),
    path('deleteLanguage/<int:pk>/', views.tLanguageDeleteView.as_view(),name='deleteLanguage'),
# Roles de transcripción
    path('tRoles_trans/', views.tRoles_trans_view, name='tRoles_trans'),
    path('createtRoles_trans', views.tRoles_transCreateView.as_view(),name='createtRoles_trans'),
    path('updatetRoles_trans/<int:pk>/', views.tRoles_transUpdateView.as_view(),name='updatetRoles_trans'),
    path('deletetRoles_trans/<int:pk>/', views.tRoles_transDeleteView.as_view(),name='deletetRoles_trans'),

# Etapas de transcripción
    path('tEtapas_trans/', views.tEtapas_trans_view, name='tEtapas_trans'),
    path('createtEtapas_trans', views.tEtapas_transCreateView.as_view(),name='createtEtapas_trans'),
    path('updatetEtapas_trans/<int:pk>/', views.tEtapas_transUpdateView.as_view(),name='updatetEtapas_trans'),
    path('deletetEtapas_trans/<int:pk>/', views.tEtapas_transDeleteView.as_view(),name='deletetEtapas_trans'),

# Transcripciones
    path('folder/<int:folder_id>/', views.folder_detail, name='folder_detail'),
    path('upload/', views.upload_file, name='upload_file'),

    path('tTranscript/', views.tTranscript_view, name='tTranscript'),
    path('createtTranscript', views.tTranscriptCreateView.as_view(),name='createtTranscript'),
    path('updatetTranscript/<int:pk>/', views.tTranscriptUpdateView.as_view(),name='updatetTranscript'),
    path('deletetTranscript/<int:pk>/', views.tTranscriptDeleteView.as_view(),name='deletetTranscript'),
    
# Personas

    path('tPerson/', views.tPerson_view, name='tPerson'),
    path('createtPerson', views.tPersonCreateView.as_view(),name='createtPerson'),
    path('updatetPerson/<int:pk>/', views.tPersonUpdateView.as_view(),name='updatetPerson'),
    path('deletetPerson/<int:pk>/', views.tPersonDeleteView.as_view(),name='deletetPerson'),

# Speakers

]

vocali/vocali/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Aplicaciones.urls')),
]

if settings.DEBUG:  # Solo durante el desarrollo
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Tus otras URL patterns aquí...

vocali/Aplicaciones/models.py
from django.db import models
import requests
from django.contrib.auth.models import User, AbstractUser
from django.contrib.auth.backends import ModelBackend
from django.core.exceptions import PermissionDenied
from django.contrib.postgres.fields import ArrayField
from django.db.models import JSONField
from django.contrib.auth import get_user_model

# Create your models here.

class Company(models.Model):
    company_id = models.AutoField(primary_key=True)
    company_nit = models.CharField(max_length=15,blank=True, null=True)
    company_name = models.CharField(max_length=50,blank=True, null=True)
    company_short_name = models.CharField(max_length=12,blank=True, null=True) 
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Empresa"
        verbose_name_plural = "Empresas"
        
    def __str__(self):
     return str(self.company_id) # Mostrar el nombre de la empresa en lugar de "object (x)"

    
    # def __str__(self):
    #     return self.empresa_id
    
class Usr_company(models.Model):
    usr_company_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    usr_mobile = models.CharField(max_length=15,blank=True, null=True)
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Usuario Autorizado"
        verbose_name_plural = "Usuario Autorizado"
    
    def __str__(self):
        return self.company_id
    # def __str__(self):
    #     return str(self.company_nom) 



    
class tType_identity(models.Model):
    id_type_identity = models.AutoField(primary_key=True)
    name_type_identity = models.CharField(max_length=50,blank=True, null=True)
    short_name_type_identity = models.CharField(max_length=50,blank=True, null=True)
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Tipo de Identidad"
        verbose_name_plural = "Tipos de Identidades"
        
    def __str__(self):
        return self.name_type_identity  

class tLanguage(models.Model):
    Id_language = models.AutoField(primary_key=True)
    description_language = models.CharField(max_length=30,blank=True, null=True)
    short_description_language = models.CharField(max_length=3,blank=True, null=True)
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Lenguaje"
        verbose_name_plural = "Lenguajes"
        
    def __str__(self):
        return self.description_language 

class tRoles_trans(models.Model):
    id_roles_trans = models.AutoField(primary_key=True)
    rol_transcrip_name = models.CharField(max_length=50,blank=True, null=True)
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Rol"
        verbose_name_plural = "Roles"
        
    def __str__(self):
        return self.rol_transcrip_name 

class tJson_trans(models.Model):
    idjson_trans = models.AutoField(primary_key=True)
    json_trans = JSONField(blank=True, null=True) # JSON data from the external URL
    json_url_trans = models.CharField(max_length=100, blank=True, null=True) # URL to fetch JSON data
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Json"
        verbose_name_plural = "Json's"

    def _str_(self):
        return str(self.json_trans) # Return the JSON

    def fetch_json(self):
        if self.json_url_trans:
            response = requests.get(self.json_url_trans)
            if response.status_code == 200:
                self.json_trans = response.json()
                self.save()
            else:
                response.raise_for_status()
        else:
            raise ValueError("No URL defined for this object")
        
class tEtapas_trans(models.Model):
    id_etapa_trans = models.AutoField(primary_key=True)
    etapa_name = models.CharField(max_length=50,blank=True, null=True)
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Etapa"
        verbose_name_plural = "Etapas"
        
    def __str__(self):
        return self.etapa_name 

class Folder(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    parent_folder = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Carpeta"
        verbose_name_plural = "Carpetas"
        
    def __str__(self):
        return self.name
    
class tTranscript(models.Model):
    id_transcript = models.AutoField(primary_key=True)
    number_proces_transcript = models.CharField(max_length=15,blank=True, null=True)
    name_transcript = models.CharField(max_length=60,blank=True, null=True)
    date_transcript = models.DateTimeField(auto_now=True)
    description_transcript = models.CharField(max_length=1024,blank=True, null=True)
    s3_video_url = models.CharField(max_length=100,blank=True, null=True) # url con procedimiento de disminución
    idjson_trans = models.ForeignKey(tJson_trans, on_delete=models.CASCADE, null=True) 
    id_etapa_trans = models.ForeignKey(tEtapas_trans, on_delete=models.CASCADE, null=True) 
    id_folder = models.ForeignKey(Folder, on_delete=models.CASCADE, null=True)
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Transcripción"
        verbose_name_plural = "Transcripciones"
        
    def __str__(self):
        return self.name_transcript 
    

class tPerson(models.Model):
    id_person = models.AutoField(primary_key=True)
    id_type_identity = models.ForeignKey(tType_identity, on_delete=models.CASCADE, null=True)
    identity_person = models.CharField(max_length=15,blank=True, null=True)
    first_name_person = models.CharField(max_length=30,blank=True, null=True)
    last_name_person = models.CharField(max_length=30,blank=True, null=True)
    alias_person = models.CharField(max_length=60,blank=True, null=True)
    description_person = models.CharField(max_length=1024,blank=True, null=True)
    Id_language = models.ForeignKey(tLanguage, on_delete=models.CASCADE, null=True)
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Persona"
        verbose_name_plural = "Personas"
        
    def __str__(self):
        return self.name_person 

# models File upload.
class UploadedFile(models.Model):
    file = models.FileField(upload_to='upload/')

# Speaker esta tabla el objetivo de asociar una persona con una transcripción y aquí se le agrega cual es el rol dentro de la transcripción
class tSpeakers_trans(models.Model): 
    id_spk_trans = models.AutoField(primary_key=True)
    name_spk_trans = models.CharField(max_length=50,blank=True, null=True)
    spks_timestamp_trans = ArrayField(models.DateTimeField(), null=True) #arreglo 
    id_transcript = models.OneToOneField(tTranscript, on_delete=models.CASCADE)
    id_person = models.OneToOneField(tPerson, on_delete=models.CASCADE)
    id_roles_trans = models.OneToOneField(tRoles_trans, on_delete=models.CASCADE)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    uploaded_file = models.ForeignKey(UploadedFile, on_delete=models.CASCADE, null=True, blank=True, related_name="transcripts")
    enable = models.BooleanField(default=False)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Speaker"
        verbose_name_plural = "Speakers"
        
    def __str__(self):
        return self.name_spk_trans 

vocali/Aplicaciones/forms.py
# forms.py
from django import forms
from .models import *

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ['file']

class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['name', 'parent_folder']


class tLanguageForm(forms.ModelForm):
    class Meta:
        model = tLanguage
        fields = ['description_language','short_description_language','enable']

class tType_identityForm(forms.ModelForm):
    class Meta:
        model = tType_identity
        fields = ['name_type_identity','short_name_type_identity','enable']

class tRoles_transForm(forms.ModelForm):
    class Meta:
        model = tRoles_trans
        fields = ['rol_transcrip_name','enable']

class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['name', 'parent_folder']
        
class tEtapas_transForm(forms.ModelForm):
    class Meta:
        model = tEtapas_trans
        fields = ['etapa_name','enable']

class tTranscriptForm(forms.ModelForm):
    id_etapa_trans = forms.ModelChoiceField(queryset=tEtapas_trans.objects.all(), required=True, label='Etapa')
    class Meta:
        model = tTranscript
        fields = ['number_proces_transcript','name_transcript','description_transcript','s3_video_url','idjson_trans','id_etapa_trans','id_folder','enable']



class tPersonForm(forms.ModelForm):
    class Meta:
        model = tPerson
        fields = ['id_type_identity','identity_person','first_name_person','last_name_person','alias_person','description_person','Id_language','enable']

class tSpeaker_transForm(forms.ModelForm):
     class Meta:
         model = tSpeakers_trans
         fields = ['name_spk_trans','id_transcript','id_person','id_roles_trans','uploaded_file','enable']








    

vocali/Aplicaciones/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Sistema de Transcripción Iteligente| VOCALI </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="/static/login/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/login/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/login/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/login/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('/static/login/images/bg-01.jpg');">
			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
				<form class="login100-form validate-form flex-sb flex-w" action="{% url 'admin:login' %}" method="post">
					{% csrf_token %} 
					<span class="login100-form-title p-b-53">
						<img src="/static/assets/images/Logopeq.png" alt="" />
					</span>
					<span class="login100-form-title p-b-33">
						Sign into your account
					</span>

					
					<div class="p-t-31 p-b-9">
						<span class="txt1">
							Usuario
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Username is required">
						<input class="input100" type="text" id="username" name="username" >
						<span class="focus-input100"></span>
					</div>
					
					<div class="p-t-13 p-b-9">
						<span class="txt1">
							Contraseña
						</span>

						<a href="#" class="txt2 bo1 m-l-5">
							Forgot?
						</a>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" id="password">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Sign In
						</button>
					</div>

					<div class="w-full text-center p-t-55">
						<span class="txt2">
							Not a member?
						</span>

						<a href="#" class="txt2 bo1">
							Sign up now
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="/static/login/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/login/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/daterangepicker/moment.min.js"></script>
	<script src="/static/login/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/login/js/main.js"></script>

</body>
</html>

vocali/Aplicaciones/templates/loginold.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>Sistema de Transcripción Iteligente| VOCALI </title>
  <!-- MDB icon -->
  <link rel="icon" href="/static/assets/images/icons/favicon.ico" type="image/x-icon" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
  <!-- MDB -->
  <link rel="stylesheet" href="/static/assets/css/bootstrap-login-form.min.css" />
  <style>
    .gradient-custom {
      /* fallback for old browsers */
      background: #6a11cb;

      /* Chrome 10-25, Safari 5.1-6 
      background: -webkit-linear-gradient(to right, rgba(7,28,43, 1), rgba(28, 61, 91, 1));*/

      background: repeating-linear-gradient(0deg, rgb(29, 7, 43), rgb(201, 114, 217) 10%, rgb(30, 7, 43) 1000%);


      /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ 
      background: linear-gradient(to right, rgba(7,28,43, 1), rgba(28, 61, 91, 1)) */
      background: repeating-linear-gradient(0deg, rgb(29, 7, 43), rgb(201, 114, 217) 10%, rgb(30, 7, 43) 150%);
    }

    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      /* Agrega una sombra */
    }
  </style>
</head>
<body> 
  <!-- Start your project here-->
  <section class="vh-100" style="background-image: url('/static/login/images/bg-01.jpg');">
    <section class="vh-100 gradient-custom">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-6 col-lg-5 d-none d-md-block">
                  <img 
                    
                    src="/static/assets/images/bg_4.jpg" alt="login form" class="img-fluid"
                    style="border-radius: 1rem 0 0 1rem;" />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">

                    <form action="{% url 'admin:login' %}" method="post">
                      {% csrf_token %} 


                      <a href="/" class="logo d-flex align-items-center">
                        <div class="d-flex align-items-center mb-3 pb-1">
                          <!--<i class="fas fa-cubes fa-2x me-3" style="color: #6b0c93;"></i>  width="150" height="70"  -->
                          <img src="/static/assets/images/Logo.png" alt="" />

                        </div>
                      </a>

                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>

                      <div class="form-outline mb-4">
                        <input type="text" id="form2Example17" class="form-control form-control-lg" id="username"
                          name="username" />
                        <label class="form-label" for="form2Example17">Usr Name</label>
                      </div>

                      <div class="form-outline mb-4">
                        <input type="password" id="form2Example27" class="form-control form-control-lg" id="password"
                          name="password">
                        <label class="form-label" for="form2Example27">Password</label>
                      </div>

                      <div class="pt-1 mb-4">
                        <input type="submit" value="Log In" class="btn btn-dark btn-lg btn-block">
                        

                      </div>

                      <a class="small text-muted" href="#!">Forgot password?</a>
                      <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="#!"
                          style="color: #393f81;">Register here</a></p>
                      <a href="#!" class="small text-muted">Terms of use.</a>
                      <a href="#!" class="small text-muted">Privacy policy</a>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End your project here-->

    <!-- MDB -->
    <script type="text/javascript" src="/static/assets/js/mdb.min.js"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
</body>

</html>

vocali/Aplicaciones/templates/principal.html
{% extends 'index_master.html' %}
{% block content %}

<div class="pagetitle">
  <h1>Welcome, {{user.first_name}} {{user.username}} </h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/principal/">Home</a></li>
      <li class="breadcrumb-item">Pages</li>
      <li class="breadcrumb-item active">principal</li>
    </ol>
  </nav>
</div><!-- End Page Title -->

<section class="section">
  <div class="row">
    <div class="col-lg-6">

      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Últimas Transcripciones</h5>
          <a href="{% url 'upload_file' %}" class="btn btn-primary">
            <i class="bi bi-soundwave"></i> Nueva Transcripción
          </a>

        </div>
      </div>

    </div>

  </div>
  <div class="row">
    <div class="col-lg-12">

      <div class="card">
        <div class="card-body">
          <!-- Table with stripped rows -->
          <table class="table datatable">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Número de ID</th>
                <th scope="col">Nombre/Tipo</th>
                <th scope="col">Duración</th>
                <th scope="col">Fecha</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">1</th>
                <td>12345678913456789</td>
                <td>Andrade - Lopez AUDIENCIA</td>
                <td>28:00</td>
                <td>2016-05-25</td>
              </tr>
              <tr>
                <th scope="row">2</th>
                <td>123456789134533333</td>
                <td>Gonzalez - Arboleda Audio</td>
                <td>3:15</td>
                <td>2014-12-05</td>
              </tr>
              <tr>
                <th scope="row">3</th>
                <td>1234567891345333444</td>
                <td>Compensar - Rama Judicial</td>
                <td>45:30</td>
                <td>2011-08-12</td>
              </tr>
              <tr>
                <th scope="row">4</th>
                <td>1234567891345333444</td>
                <td>Rama Judicial - Cundinamarca</td>
                <td>34:45</td>
                <td>2012-06-11</td>
              </tr>

            </tbody>
          </table>
          <!-- End Table with stripped rows -->

        </div>
      </div>

    </div>
  </div>
</section>

<section class="section">
  <div class="user-folders">
    <a class="nav-link collapsed">
      <!-- <i class="bi bi-folder"></i>
            <span>Tus CASOS:</span> -->

      <ul class="sidebar-nav">
        {% for folder in top_level_folders %}
        <li class="nav-item">
          <a class="nav-link collapsed" href="{% url 'folder_detail' folder.id %}">
            <i class="bi bi-folder"></i>
            <span>{{ folder.name }}</span>
          </a>
          {% with subfolders=folder.folder_set.all %}
          {% if subfolders %}
          <ul>
            {% for subfolder in subfolders %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'folder_detail' subfolder.id %}">
                <i class="bi bi-folder"></i>
                <span>{{ subfolder.name }}</span>
              </a>
            </li>
            {% endfor %}
          </ul>
          {% endif %}
          {% endwith %}
        </li>
        {% endfor %}
      </ul>
    </a>
  </div>

  <!-- Botón para abrir la modal -->
  <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#verticalycentered">
    <i class="bi bi-folder"></i>
    + Crear Carpeta
  </button>

  <!-- Modal para crear carpeta -->
  <div class="modal fade" id="verticalycentered" tabindex="-1" aria-labelledby="verticalycenteredLabel"
    aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="verticalycenteredLabel">Crear Nueva Carpeta</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="post" action="{% url 'principal' %}">
            {% csrf_token %}
            <div class="mb-3">
              <label for="folderName" class="form-label">Nombre de la Carpeta:</label>
              <input type="text" class="form-control" id="folderName" name="name" required>
            </div>
            <div class="mb-3">
              <label for="parentFolder" class="form-label">Carpeta superior (opcional):</label>
              <select class="form-control" id="parentFolder" name="parent_folder">
                <option value="">Ninguna</option>
                {% for folder in top_level_folders %}
                <option value="{{ folder.id }}">{{ folder.name }}</option>
                {% endfor %}
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Crear Carpeta</button>
          </form>
        </div>
      </div>
    </div>
  </div>


  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
</section>

{% endblock %}